---
- name: Check if SSH key already exists
  ansible.builtin.stat:
    path: "{{ ssh_keygen_storagedir }}/{{ ssh_keygen_keyname }}"
  register: _ssh_key_path

- name: Generate SSH key
  ansible.builtin.command:
    cmd: >-
      ssh-keygen
       -t {{ ssh_keygen_cipher }} {{ ssh_keygen_cipher_options }}
       -f {{ ssh_keygen_keyname }}
        {% if ssh_keygen_comment %}-C {{ ssh_keygen_comment }}{% endif %}
        {% if ssh_keygen_passphrase %}-P {{ ssh_keygen_passphrase }}{% endif %}
    chdir: "{{ ssh_keygen_storagedir }}"
    creates: "{{ ssh_keygen_storagedir }}/{{ ssh_keygen_keyname }}.pub"
  changed_when: true
  when: not _ssh_key_path.stat.exists
